#-------------------------------
# General Site Settings

title: RITSEC
title_long: RITSEC Student Computing Security Club
motto: Security Through Community
email: ritsecclub@gmail.com
description: >
  RITSEC Student Computing Security Club
twitter: RITSECclub
github: 
  name: ritsec
  project: ritsec.github.io
facebook_page: RITSEC
facebook_group: RITSEC.group
youtube: UCfakBry_pXOvaPrVVr1SH-Q

#-------------------------------
# Main Image Slider Settings
slider:
  - image: ISTS_0.jpg
  - image: ISTS_1.jpg
  - image: ISTS_2.jpg
  - image: ISTS_3.jpg
  - image: ISTS_4.jpg
  - image: ISTS_5.jpg

#-------------------------------
# Navbar Settings
favicon: favicon.png
navbar-brand:
  image: logo_header.png
  link: '/index.html'

navbar:
  - name: 'Home'
    link: 'index.html'
  - name: 'About'
    link: 'about.html'
  - name: Members
    subitems:
    - name: 'EBoard'
      link: 'eboard.html'
    - name: 'Past EBoards'
      link: 'past-eboards.html'
    - name: 'Alumni'
      link: 'alumni.html'
  - name: 'Events'
    link: 'events.html'
  - name: 'Sponsors'
    link: 'sponsors.html'

#-------------------------------
# EBoard Settings

eboard_roles:
  - name: President
    appointee: Micah Martin
    image: president.jpg
    description: >
      Micah Martin is a third year Computing Security student at RIT. He competes 
      on the school's CCDC team and loves helping with and competing in security 
      competitions. Micah's technical focus is primary on Linux systems and email 
      servers. He loves helping out the community and learning with others. If he 
      isn't sleeping in the computer labs, he can be found sleeping out in the woods. 
      You can contact him at mmartin@sparsa.org.
  - name: Head of Education
    appointee: Russell Babarsky
    image: hoe.jpg
    description: >
      Russell Babarsky is a third-year computing security major. His passion lies 
      in pen testing and exploit development. Besides security, he enjoys hiking, 
      baseball, and listening to music.
  - name: Head of Research
    appointee: Nick O'Brien
    image: hor.jpg
    description: >
      description...
  - name: Competition Architect
    appointee: Sean Newman
    image: ca.jpg
    description: >
      description...
  - name: Treasurer
    appointee: Shannon McHale
    image: treasurer.jpg
    description: >
      The Treasurer...
  - name: Secretary
    appointee: Jack McKenna
    image: secretary.jpg
    description: >
      description...
  - name: Director of Public Relations
    appointee: Alicen Dipiano
    image: dpr.jpg
    description: >
      description...
  - name: Operations Lead
    appointee: Brandon Adler
    image: ol.jpg
    description: >
      description...
  - name: Tech Lead
    appointee: Scott Brink
    image: tl.jpg
    description: >
      description...

#-------------------------------
# About Us

about_us_short: >
  <p>RITSEC is a student-run organization dedicated to educating and preparing RIT students to compete in security-related
  competitions, as well as showcasing RIT student talent in the current world of security today.</p>
about_us_long: >
  <br><br>
  <p>RITSEC is a student-run organization dedicated to educating and preparing RIT students to compete in security-related
  competitions, as well as showcasing RIT student talent in the current world of security today. Whether you're new to computing security or a veteran, RITSEC has a place for you.
  </p>
  <p>
  We believe security is for anyone who wants to learn and center our activities around multiple aspects of security. This includes
  live individual and team-based competitions, hands-on training, student run research, and sponsor talks. Our security exercises
  cover a wide variety of areas in computing security, including penetration testing, Windows and Linux server hardening,
  web security, network services, and more!</p>
  <p>In 2018, the Security Practices And Research Student Association (SPARSA) and RIT Competitive Cybersecurity Club (RC3) merged to become RITSEC.
  As a result, the security community at RIT became more unified as the major and industry grew.</p>
  <br><br><br><br>

#-------------------------------
# Events
events:
- name: Weekly Education Meeting
  description: >
    Join us every Friday from 12:00-2:00PM for a hands-on lab and presentation to learn a weekly security topic.
  image: meetings.png
- name: Weekly Research Meeting
  description: >
    Every Friday from 2:00-4:00PM, RITSEC hosts a research section for students to present on security topics that interest them.
    Please contact the Head of Research to submit a presentation.
  image: meetings.png
- name: RITSEC CTF
  description: >
    The RITSEC CTF is a security-focused competition that features the following categories: 
    Binary, Crypto, Forensics, Programming, and Web. We welcome beginners and more advanced security friends!
  image: ists.jpg
- name: IRSeC
  description: >
    The Incident Responsive Security Competition is our beginner friendly wargame where we invite seasoned penetration testers to come pwn your boxes. The best way to learn is a trial by fire, so strap on your blue team helmets, it's time to go to war.
  image: hacknights.jpg
- name: ISTS
  description: >
    The Information Security Talent Search (ISTS) competition is an annual three-day cyber attack/defend competition
    hosted by us. Competitors are faced with a wide variety of challenges which are designed to cover as many facets of
    computing security, system administration, networking, and programming as we possibly can. These challenges include
    code review, architecture design, incident response, and policy writing -- all while defending a completely
    student-built infrastructure. Read more about the competition <a href="https://ists.ritsec.club">here</a>.
  image: ists.jpg
