#-------------------------------
# General Site Settings

title: RITSEC
title_long: RITSEC Student Computing Security Club
motto: Security Through Community
email: ritsecclub@gmail.com
description: >
  RITSEC Student Computing Security Club
twitter: RITSECclub
github: 
  name: ritsec
  project: ritsec.github.io
facebook_page: RITSEC
facebook_group: RITSEC
youtube: UCfakBry_pXOvaPrVVr1SH-Q
#slack: SPARSA

#-------------------------------
# Main Image Slider Settings
slider:
  - image: ISTS_0.jpg
  - image: ISTS_1.jpg
  - image: ISTS_2.jpg
  - image: ISTS_3.jpg
  - image: ISTS_4.jpg
  - image: ISTS_5.jpg

#-------------------------------
# Navbar Settings
favicon: favicon.png
navbar-brand:
  image: logo_header.png
  link: '/index.html'

navbar:
  - name: 'Home'
    link: 'index.html'
  - name: 'About'
    link: 'about.html'
    subitems:
    - name: 'Alumni'
      link: 'alumni.html'
    - name: 'Past EBoards'
      link: 'past-eboards.html'
  - name: 'EBoard'
    link: 'eboard.html'
  - name: 'Events'
    link: 'events.html'
  - name: 'ISTS'
    link: 'https://ists.sparsa.org'
  - name: 'Sponsors'
    link: 'sponsors.html'

#-------------------------------
# EBoard Settings

eboard_roles:
  - name: President
    appointee: Micah Martin
    image: president.jpg
    description: >
      Micah Martin is a third year Computing Security student at RIT. He competes 
      on the school's CCDC team and loves helping with and competing in security 
      competitions. Micah's technical focus is primary on Linux systems and email 
      servers. He loves helping out the community and learning with others. If he 
      isn't sleeping in the computer labs, he can be found sleeping out in the woods. 
      You can contact him at mmartin@sparsa.org.
  - name: Head of Education
    appointee: Russell Babarsky
    image: hoe.jpg
    description: >
      Russell Babarsky is a third-year computing security major. His passion lies 
      in pen testing and exploit development. Besides security, he enjoys hiking, 
      baseball, and listening to music.
  - name: Head of Research
    appointee: Nick O'Brien
    image: hor.jpg
    description: >
      description...
  - name: Competition Architect
    appointee: Sean Newman
    image: ca.jpg
    description: >
      description...
  - name: Treasurer
    appointee: Shannon McHale
    image: treasurer.jpg
    description: >
      The Treasurer...
  - name: Secretary
    appointee: Jack McKenna
    image: secretary.jpg
    description: >
      description...
  - name: Director of Public Relations
    appointee: Alicen Dipiano
    image: dpr.jpg
    description: >
      description...
  - name: Operations Lead
    appointee: Brandon Adler
    image: ol.jpg
    description: >
      description...
  - name: Tech Lead
    appointee: Scott Brink
    image: tl.jpg
    description: >
      description...

#-------------------------------
# About Us

about_us_short: >
  The Security Practices and Research Student Association (SPARSA) was founded 
  in the wake of 9/11 by RIT students Jared Campbell, Eric Linden and Matt Hile. 
  The initial faculty advisor was Dr. Samuel McQuade - Former Program Chair of 
  The Center for Multidisciplinary Studies at RIT.
about_us_long: >
  <p>The Security Practices and Research Student Association (SPARSA) was founded 
  in the wake of 9/11 by RIT students Jared Campbell, Eric Linden and Matt Hile. 
  The initial faculty advisor was Dr. Samuel McQuade - Former Program Chair of 
  The Center for Multidisciplinary Studies at RIT.</p>
  <br>
  <p>Since its inception, SPARSA has been a student-run organization that addresses 
  security-related issues and how these issues affect multiple majors and disciplines. 
  The ultimate goal of this organization is to provide students with experience in 
  information security and job opportunities in information security (infosec) related 
  fields. This includes aiding members in the search for both cooperative education 
  (co-op) and full-time employment opportunities.</p>
  <br>
  <p>To meet this goal, SPARSA hosts and participates in research and development of 
  security tools and policies. In addition, SPARSA provides consulting for organizations 
  in need of improved security. SPARSA also seeks to build and maintain relationships with 
  local and national security related organizations. This includes social networking with 
  security professionals and hosting conferences, symposia, and other security-related 
  events to spur growth in this area.</p>
  <br>
  <p>As security becomes progressively more important in our increasingly global world, 
  SPARSA will help students remain on top of their game and up to date with the latest 
  security issues, practices, and research. "Today individuals, families, organizations, 
  communities and our nation face unprecedented combinations of cyber and physical security 
  threats to both cyber and physical assets. The challenge is to enhance security capabilities 
  at all levels of society by developing better security technologies, and by providing 
  education and training in the use and management of security technologies" (Dr. Samuel McQuade)</p>
  <br>

#-------------------------------
# Events
events:
- name: Weekly Education Meeting
  description: >
    Join us every Friday from 12:00-2:00PM for a hands-on lab and presentation to learn a weekly security topic.
  image: meetings.png
- name: Weekly Research Meeting
  description: >
    Every Friday from 2:00-4:00PM, RITSEC hosts a research section for students to present on security topics that interest them.
    Please contact the Head of Research to submit a presentation.
  image: meetings.png
- name: RITSEC CTF
  description: >
    The RITSEC CTF is a security-focused competition that features the following categories: 
    Binary, Crypto, Forensics, Programming, and Web. We welcome beginners and more advanced security friends!
  image: ists.jpg
- name: IRSeC
  description: >
    The Incident Responsive Security Competition is our beginner friendly wargame where we invite seasoned penetration testers to come pwn your boxes. The best way to learn is a trial by fire, so strap on your blue team helmets, it's time to go to war.
  image: hacknights.jpg
- name: ISTS
  description: >
    The Information Security Talent Search (ISTS) competition is an annual three-day cyber attack/defend competition
    hosted by us. Competitors are faced with a wide variety of challenges which are designed to cover as many facets of
    computing security, system administration, networking, and programming as we possibly can. These challenges include
    code review, architecture design, incident response, and policy writing -- all while defending a completely
    student-built infrastructure. Read more about the competition <a href="https://ists.ritsec.club">here</a>.
  image: ists.jpg
